### ISSUE TITLE
check whether freshclam daemon is running

### ISSUE THREAD

**Issue by jksinton** [crylium/clamav-daily#4]
Instead of removing the log file for freshclam, could you check whether it's running as a daemon?

If it is, you don't really need to update the database, as it's already updating the database based on the config settings.

If it's not running as a daemon, then you should be able to run freshclam without the lock error.

**Comment by lisenet** [comment]
You can check if the file is in use by the daemon. And you would be right, you shouldn't need to update the DB in such case.
