### ISSUE TITLE
Hairloom mailx is no longer available

### ISSUE THREAD

**Issue by nucl123** [crylium/clamav-daily#7]
Thanks for the script, but heirloom-mailx is not available, please update the script to use something like msmtp 
https://wiki.debian.org/msmtp

`Package heirloom-mailx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

**Comment by lisenet** [comment]
Hi @nucl123, what OS are you on?

**Comment by nucl123** [comment]
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

@lisenet

**Comment by nucl123** [comment]
`NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
`

@lisenet

**Comment by lisenet** [comment]
Thanks, please use `bsd-mailx` package.

**Comment by nucl123** [comment]
ok., thanks.

**Comment by nucl123** [comment]
one more question please.
is the log rotation handled by this script? or can you please suggest how to include it.
like, to remove the generated log files after the email is sent.

**Comment by lisenet** [comment]
Log rotation is not handled by the script. You can use logrotate to achieve that if required. Simply add your log rotation config to `/etc/logrotate.d/` and you should be good to go, e.g.:

```
/var/log/clamav/*.log {
  daily
  rotate 0
}
```

When rotate count is set to 0, old versions are removed rather than rotated.
